### ISSUE TITLE
Hello! can you help me?

### ISSUE THREAD

**Issue by manel00** [pratapvardhan/notebooks#2]
I'm interested to replicate your plot, but the problem is my data, it's:

```
+-------+-------------+---------+---------+
|       | country     | date    |   value |
|-------+-------------+---------+---------|
| 22106 | Afghanistan | 3/2/20  |       0 |
| 13826 | Afghanistan | 2/28/20 |       0 |
```

What should i do because im stucked with this part (getting crash):

`group_lk = newdf.set_index('country')['country'].to_dict()`

Also: How would you do the racechart with date? Thanks ;)

**Comment by pratapvardhan** [comment]
@manel00 -- Sorry, didn't look into this. Could you provide the detail log error? Suspecting it to be a memory error due to size perhaps?
